# Generated by Django 5.2 on 2025-05-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Services", "0003_url_clicks_per_day_url_clicks_per_month"),
    ]

    operations = [
        migrations.AlterField(
            model_name="url",
            name="alias",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
